DatabaseServer: localhost
DatabaseName: PowerDeliveryASPNETMVC4
WebServer: localhost
WebPort: "80"
WebSite: PowerDeliveryASPNETMVC4
WebURL: "http://localhost/PowerDeliveryASPNETMVC4"
UnitTestsPath: UnitTests\PowerDeliveryASPNETMVC4.Tests.dll
BuildConfguration: Release