Settings:
    DBServer: localhost
    DBName: PowerDeliveryASPNETMVC4_Local

MSBuild:
    PowerDeliveryASPNETMVC4:
        ProjectFile: PowerDeliveryASPNETMVC4.sln
        Properties: 
            DeployOnBuild: true
            PublishProfile: Default

Assets:
    WebSite:
        Path: PowerDeliveryASPNETMVC4\DeploymentPackage\PowerDeliveryASPNETMVC4.zip
        Destination: PowerDeliveryASPNETMVC4\DeploymentPackage
    AcceptanceTests:
        Path: PowerDeliveryASPNETMVC4.Acceptance\bin\Debug\*.* 
        Destination: AcceptanceTests
    UnitTests:
        Path: PowerDeliveryASPNETMVC4.Tests\bin\Debug\*.* 
        Destination: UnitTests

WebDeploy:
    PowerDeliveryASPNETMVC4:
        WebComputer: localhost
        WebPort: 8081
        WebSite: PowerDeliveryASPNETMVC4_Local
        WebPassword: "!hafoi^45"
        WebURL: http://localhost:8081/
        Package: PowerDeliveryASPNETMVC4\DeploymentPackage\PowerDeliveryASPNETMVC4.zip
        Parameters:
            "IIS Web Application Name": PowerDeliveryASPNETMVC4_Local
            "DefaultConnection-Web.config Connection String": Data Source=localhost;Initial Catalog=PowerDeliveryASPNETMVC4_Local;Integrated Security=SSPI

Roundhouse:
    PowerDeliveryASPNETMVC4:
        Server: localhost
        Database: PowerDeliveryASPNETMVC4_Local
        ScriptsDir: PowerDeliveryASPNETMVC4DB