DBServer: localhost
DBName: PowerDeliveryASPNETMVC4_Test
WebPassword: aBcD3fg33
WebComputer: localhost
WebPort: 8083
WebURL: http://localhost:8083/
WebSite: PowerDeliveryASPNETMVC4_Test
ConnectionString: Data Source=localhost;Initial Catalog=PowerDeliveryASPNETMVC4_Test;Integrated Security=SSPI