Settings:
    DBServer: localhost
    DBName: PowerDeliveryASPNETMVC4_Test

MSBuild:
    PowerDeliveryASPNETMVC4:
        ProjectFile: PowerDeliveryASPNETMVC4.sln
        Properties: 
            DeployOnBuild: true
            PublishProfile: Default

Assets:
    WebSite:
        Path: PowerDeliveryASPNETMVC4\DeploymentPackage\PowerDeliveryASPNETMVC4.zip
        Destination: WebSites\PowerDeliveryASPNETMVC4
    AcceptanceTests:
        Path: PowerDeliveryASPNETMVC4.Acceptance\bin\Debug\*.* 
        Destination: AcceptanceTests
    UnitTests:
        Path: PowerDeliveryASPNETMVC4.Tests\bin\Debug\*.* 
        Destination: UnitTests
    Databases:
        Path: PowerDeliveryASPNETMVC4DB
        Destination: Databases
        Recurse: true

WebDeploy:
    PowerDeliveryASPNETMVC4:
        WebComputer: localhost
        WebPort: 8083
        WebSite: PowerDeliveryASPNETMVC4_Test
        WebPassword: "!hafoi^45"
        WebURL: http://localhost:8083/
        Package: WebSites\PowerDeliveryASPNETMVC4\PowerDeliveryASPNETMVC4.zip
        Parameters:
            "IIS Web Application Name": PowerDeliveryASPNETMVC4_Test
            "DefaultConnection-Web.config Connection String": Data Source=localhost;Initial Catalog=PowerDeliveryASPNETMVC4_Test;Integrated Security=SSPI

Roundhouse:
    PowerDeliveryASPNETMVC4:
        Server: localhost
        Database: PowerDeliveryASPNETMVC4_Test
        ScriptsDir: Databases\PowerDeliveryASPNETMVC4DB