DatabaseServer: localhost
DatabaseName: PowerDeliveryASPNETMVC4_CapacityTest
WebServer: localhost
WebPort: "8084"
WebSite: PowerDeliveryASPNETMVC4_CapacityTest
WebURL: "http://localhost:8084"
UnitTestsPath: UnitTests\PowerDeliveryASPNETMVC4.Tests.dll
BuildConfiguration: Release