DatabaseServer: localhost
DatabaseName: PowerDeliveryASPNETMVC4_Local
WebServer: localhost
WebPort: "8081"
WebSite: PowerDeliveryASPNETMVC4_Local
WebURL: "http://localhost:8081"
UnitTestsPath: PowerDeliveryASPNETMVC4.Tests\bin\Debug\PowerDeliveryASPNETMVC4.Tests.dll
BuildConfiguration: Debug